// <auto-generated />
namespace HackathonPMA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HackathonPMAModelsEntitiesProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HackathonPMAModelsEntitiesProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201510172126152_HackathonPMA.Models.Entities.Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
