// <auto-generated />
namespace HackathonPMA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HackathonPMAModelsApplicationDbContextAspNetUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HackathonPMAModelsApplicationDbContextAspNetUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201510221907160_HackathonPMA.Models.ApplicationDbContext.AspNetUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
