// <auto-generated />
namespace HackathonPMA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class HackathonPMAModelsApplicationDbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HackathonPMAModelsApplicationDbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201510151120380_HackathonPMA.Models.ApplicationDbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
