//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonPMA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Quantity must be a number")]
        public Nullable<int> Quantity { get; set; }

        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Price must be a number")]
        public Nullable<double> Price { get; set; }
    }
}
